### ISSUE TITLE
Panic on "-\u{a0}_(__" * 8 (unexpected item body MaybeEmphasis)

### ISSUE THREAD

**Issue by oberien** [raphlinus/pulldown-cmark#306]
```
# MaybeEmphasis(2, true, false)
python -c "print('__{_\xa0*' * 3)" | RUST_BACKTRACE=1 cargo run -- -TFSL
# MaybeEmphasis(1, true, false)
python -c 'print("-\xa0_(__" * 8)' | RUST_BACKTRACE=1 cargo run
python -c 'print(("_preCDATA[__?" * 50000)[:209704])' | RUST_BACKTRACE=1 cargo run
python -c 'print(";*CDATA[?~~" * 8 + "*")' | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c 'print("~_f [^~" * 8 + "~_")' | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~_pre))~' * 4 + '~_')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('"*A</pre>~~' * 4 + '"*')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~_\x00</pre>.~' * 4 + '~_')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~*CDATA[}<~' * 4 + '~*')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('"_A&#x27;~~' * 4 + '"_')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('"_9)__' * 4)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~_pref$~' * 4 + '~_')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('_/_ð\x90\x80\x80._' * 2 + '_')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~_\x00&&amp;~' * 4 + '~_')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~_\x80#%~' * 4 + '~_')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('!--*f@~~' * 4 + '!--*')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('+_\x00#__' * 4)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~*9"&#x27;~' * 4 + '~*')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~*address!--&#x27;~' * 4 + '~*')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print(';_A!--__' * 4)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~*CDATA[/}~' * 4 + '~*')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('@_\x00:__' * 4)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('_#_CDATA[._' * 2 + '_')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~*ssse3#%~' * 4 + '~*')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print(')_X"__' * 4)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('_*_Z\r*' * 2)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print("%_Z'__" * 4)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~_ð\x90\x80\x80>!--~' * 4 + '~_')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('&#x27;_a&amp;__' * 4)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('*\r_<__' * 4)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('> _</pre>}__' * 4)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~*\x00ð\x90\x80\x80!--~' * 4 + '~*')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~_x\\&#x27;~' * 4 + '~_')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~*CDATA[:#~' * 4 + '~*')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print("~*\x80-'~" * 4 + '~*')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('"_pre^__' * 4)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~("_CDATA[~' * 4 + '~("_')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('> _XCDATA[__' * 4)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~*pre^)~' * 4 + '~*')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('/_0&amp;__' * 4)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print(';_a&__' * 4)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~_0X[^~' * 4 + '~_')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('(*xCDATA[~~' * 4 + '(*')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~)&_CDATA[~' * 4 + '~)&_')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('%_\x00[]~~' * 4 + '%_')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('|_\x80!--__' * 4)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('{_A&amp;__' * 4)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print("~*ssse3'$~" * 4 + '~*')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('&_CDATA[=~~' * 4 + '&_')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('>_Z&__' * 4)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('>*\x80#~~' * 4 + '>*')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('{ _|__' * 4)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~&#x27;*Z"~' * 4 + '~&#x27;*')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~*CDATA[>!~' * 4 + '~*')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~*xssse3`~' * 7 + '~*')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print("~*a'[]~" * 4 + '~*')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('!--*CDATA[~~&#x27;' * 4 + '!--*')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~*x>!--~' * 4 + '~*')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('_*_f> *' * 2)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~ _$__' * 4)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('?_pre"__' * 4)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~*Z\x00&amp;~' * 4 + '~*')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~*0pre+~' * 4 + '~*')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~_9"&amp;~' * 4 + '~_')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~_à\xa0\x80>/~' * 4 + '~_')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('&amp;*CDATA[;~~' * 4 + '&amp;*')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print(';_CDATA[^~~' * 4 + ';_')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('}_9;__' * 4)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~_preA-~' * 4 + '~_')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~*x[]{~' * 4 + '~*')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print(';_CDATA[[^__' * 4)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print("/_x\\'~~" * 4 + '/_')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~_x\\u{0}+~' * 4 + '~_')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print(':*x\\"~~' * 4 + ':*')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~*9\\\\-~' * 4 + '~*')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~_A\\u{0}:~' * 4 + '~_')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~*0\\u{0}%~' * 4 + '~*')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print("~*f\\'?~" * 4 + '~*')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('{_A\\u{0}~~' * 4 + '{_')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~_A[^\\u{0}~' * 4 + '~_')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~_f-\\u{0}~' * 4 + '~_')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print("+*X\\'~~" * 4 + '+*')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~*à\xa0\x80@\\\\u{80}~' * 4 + '~*')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('&#x27;_X\\\\\\"~~' * 4 + '&#x27;_')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~\\\\\\"_à\xa0\x80]~' * 4 + '~\\\\\\"_')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~\\\\\\\\\\\\\\"_xCDATA[~' * 4 + '~\\\\\\\\\\\\\\"_')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~*X</pre>\\\\\\\\u{80}~' * 4 + '~*')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print("\\\\\\\\\\\\\\'*x;~~" * 4 + "\\\\\\\\\\\\\\'*")" | RUST_BACKTRACE=1 cargo run -- -TFSL
```

```rust
thread 'main' panicked at 'unexpected item body MaybeEmphasis(1, true, false)', src/parse.rs:2353:14
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:336
   7: pulldown_cmark::parse::item_to_event
             at src/parse.rs:2353
   8: <pulldown_cmark::parse::Parser as core::iter::traits::iterator::Iterator>::next
             at src/parse.rs:2434
   9: <&mut I as core::iter::traits::iterator::Iterator>::next
             at /rustc/befeeb7c083c9e5edddc86563cc461185d897a13/src/libcore/iter/traits/iterator.rs:2693
  10: pulldown_cmark::html::HtmlWriter<I,W>::run
             at ./src/html.rs:144
  11: pulldown_cmark::html::write_html
             at ./src/html.rs:522
  12: pulldown_cmark::main
             at src/main.rs:260
  13: std::rt::lang_start::{{closure}}
             at /rustc/befeeb7c083c9e5edddc86563cc461185d897a13/src/libstd/rt.rs:64
  14: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  15: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  16: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  17: std::rt::lang_start
             at /rustc/befeeb7c083c9e5edddc86563cc461185d897a13/src/libstd/rt.rs:64
  18: main
  19: __libc_start_main
  20: _start
```

**Comment by marcusklaas** [comment]
This is a tough one!
