### ISSUE TITLE
Panic under fuzzing

### ISSUE THREAD

**Issue by dimbleby** [raphlinus/pulldown-cmark#311]
Fuzzing at 1f3eddec88760c06c933d430f0b94be8433b9c68

```
==31516== ERROR: libFuzzer: deadly signal
    #0 0x560ec7280887 in __sanitizer_print_stack_trace (/data/developer/pulldown-cmark/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_target_1+0x1a7887)
    #1 0x560ec766238f in fuzzer::PrintStackTrace() /data/developer/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/4a41319/libfuzzer/FuzzerUtil.cpp:206
    #2 0x560ec7638c1c in fuzzer::Fuzzer::CrashCallback() /data/developer/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/4a41319/libfuzzer/FuzzerLoop.cpp:237
    #3 0x560ec7638ad7 in fuzzer::Fuzzer::StaticCrashSignalCallback() /data/developer/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/4a41319/libfuzzer/FuzzerLoop.cpp:209
    #4 0x560ec7662b62 in fuzzer::CrashHandler(int, siginfo_t*, void*) /data/developer/.cargo/git/checkouts/libfuzzer-sys-e07fde05820d7bc6/4a41319/libfuzzer/FuzzerUtilPosix.cpp:36
    #5 0x7f6e5ebbb5cf  (/lib64/libpthread.so.0+0xf5cf)
    #6 0x7f6e5e5ff206 in __GI_raise (/lib64/libc.so.6+0x36206)
    #7 0x7f6e5e6008f7 in __GI_abort (/lib64/libc.so.6+0x378f7)
    #8 0x560ec766f2f6 in std::sys::unix::abort_internal::hbfbc3e60bcc33dee (/data/developer/pulldown-cmark/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_target_1+0x5962f6)
    #9 0x560ec766a3e5 in std::process::abort::h974946bec860057b (/data/developer/pulldown-cmark/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_target_1+0x5913e5)
    #10 0x560ec761ae4b in libfuzzer_sys::initialize::_$u7b$$u7b$closure$u7d$$u7d$::h0847726d606a0f64 (/data/developer/pulldown-cmark/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_target_1+0x541e4b)
    #11 0x560ec766e138 in std::panicking::rust_panic_with_hook::h3d72e3111a3dd985 (/data/developer/pulldown-cmark/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_target_1+0x595138)
    #12 0x560ec751a1b8 in std::panicking::begin_panic::h7ebee55fcc8b0b9a (/data/developer/pulldown-cmark/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_target_1+0x4411b8)
    #13 0x560ec741d4d3 in pulldown_cmark::tree::TreePointer::unwrap::h9173fd2c24edfb13 (/data/developer/pulldown-cmark/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_target_1+0x3444d3)
    #14 0x560ec72cc183 in pulldown_cmark::parse::surgerize_tight_list::he412b2d4b0abc1c3 (/data/developer/pulldown-cmark/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_target_1+0x1f3183)
    #15 0x560ec72b3c98 in pulldown_cmark::parse::FirstPass::pop::h88af5aa00ff130bc (/data/developer/pulldown-cmark/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_target_1+0x1dac98)
    #16 0x560ec729ada4 in pulldown_cmark::parse::FirstPass::run::h1194040eee273692 (/data/developer/pulldown-cmark/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_target_1+0x1c1da4)
    #17 0x560ec72cb2f4 in pulldown_cmark::parse::Parser::new_with_broken_link_callback::h0cfb9aaa15042228 (/data/developer/pulldown-cmark/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_target_1+0x1f
22f4)
    #18 0x560ec72cab95 in pulldown_cmark::parse::Parser::new_ext::h46c40e5e66996e25 (/data/developer/pulldown-cmark/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_target_1+0x1f1b95)
    #19 0x560ec72ca67b in pulldown_cmark::parse::Parser::new::ha67151b16b9d4092 (/data/developer/pulldown-cmark/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_target_1+0x1f167b)
    #20 0x560ec71df48b in rust_fuzzer_test_input (/data/developer/pulldown-cmark/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_target_1+0x10648b)
    #21 0x560ec761aad4 in libfuzzer_sys::test_input_wrap::_$u7b$$u7b$closure$u7d$$u7d$::h1b8cd3b5c3aff08a (/data/developer/pulldown-cmark/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_target_1+0x54
1ad4)
    #22 0x560ec761f20d in std::panicking::try::do_call::he4b92c68cf7b057a (/data/developer/pulldown-cmark/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_target_1+0x54620d)
    #23 0x560ec766f678 in __rust_maybe_catch_panic (/data/developer/pulldown-cmark/fuzz/target/x86_64-unknown-linux-gnu/debug/fuzz_target_1+0x596678)

NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 2 ChangeBinInt-CopyPart-; base unit: 24cfdceed6616a5b353a3035968b8035657eb8a9
0x5c,0xd,0x2d,0x9,0x5c,0xd,0x2d,0x9,
\\\x0d-\x09\\\x0d-\x09
artifact_prefix='/data/developer/pulldown-cmark/fuzz/artifacts/fuzz_target_1/'; Test unit written to /data/developer/pulldown-cmark/fuzz/artifacts/fuzz_target_1/crash-e8ca9eaf8bd7bf4f5e2cd640869f0a78
0d57ff84
Base64: XA0tCVwNLQk=
```

I just followed the instructions for fuzzing [here](https://rust-fuzz.github.io/book/cargo-fuzz.html), with this fuzz target:

```rust
#![no_main]
#[macro_use] extern crate libfuzzer_sys;
extern crate pulldown_cmark;
use pulldown_cmark::Parser;

fuzz_target!(|data: &[u8]| {
    if let Ok(s) = std::str::from_utf8(data) {
        let _ = Parser::new(s);
    }
});
```

I expect there are more to find, the fuzzer stops after the first error.

**Comment by marcusklaas** [comment]
Thanks for reporting this. This is very useful.

Note that `Parser::new` only runs the first pass. Consume the parser, for example by `Parser::new(s).count()` to run both passes and potentially find even more bugs! ;-)

**Comment by dimbleby** [comment]
Cheers.  I've no plans to pursue the fuzzing, I just got briefly intrigued by the discussion in #308.  But it does look as though there may be some low-hanging fruit here...
