### ISSUE TITLE
Panic on "\ \\ \\\ \\\\"

### ISSUE THREAD

**Issue by mity** [raphlinus/pulldown-cmark#316]
```
$ printf '\\ \\\\ \\\\\\ \\\\\\\\\n\n' | ./pulldown-cmark
thread 'main' panicked at 'unexpected item body Backslash', src/parse.rs:2740:14
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:340
   7: pulldown_cmark::parse::item_to_event
             at src/parse.rs:2740
   8: <pulldown_cmark::parse::Parser<'a> as core::iter::traits::iterator::Iterator>::next
             at src/parse.rs:2821
   9: <&mut I as core::iter::traits::iterator::Iterator>::next
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libcore/iter/traits/iterator.rs:2730
  10: <pulldown_cmark::html::HtmlWriter<'a, I, W>>::run
             at /mnt/d/src/pulldown-cmark/src/html.rs:144
  11: pulldown_cmark::html::write_html
             at /mnt/d/src/pulldown-cmark/src/html.rs:522
  12: pulldown_cmark::main
             at src/main.rs:260
  13: std::rt::lang_start::{{closure}}
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libstd/rt.rs:64
  14: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  15: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  16: std::rt::lang_start_internal
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  17: std::rt::lang_start
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libstd/rt.rs:64
  18: main
  19: __libc_start_main
  20: _start
```

**Comment by mity** [comment]
Can be shortened to:
```
$ printf '\\ \\\\\n\n' | ./pulldown-cmark
```

**Comment by oberien** [comment]
This might be the same as #304. Interestingly the fuzzer only found the panic with `\r\r` and not `\n\n`.

**Comment by mity** [comment]
Yeah, definitely looks as a duplicate. Didn't check for duplicates after the shortening....
